# Generated by Django 5.1.2 on 2024-10-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descrição',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
