# Generated by Django 5.1.2 on 2024-10-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_descrição_remove_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_produto',
            field=models.CharField(default='000', max_length=100, unique=True),
        ),
    ]
