# Generated by Django 5.1.2 on 2024-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
