# Generated by Django 5.1.2 on 2024-10-26 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_rename_cod_produto_produto_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
