# Generated by Django 5.1.2 on 2024-10-27 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descrição',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
