# Generated by Django 5.1.2 on 2024-11-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_venda_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='code',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
